In [1]:
import os
import sys
import pandas as pd
import numpy as np 
PROJECT_ROOT = os.path.abspath("..")

if PROJECT_ROOT not in sys.path:
    sys.path.append(PROJECT_ROOT)

In [2]:
from src.loader import load_candidates
from src.preprocessing import prepare_data

In [3]:
candidates = load_candidates()

data = prepare_data(candidates)

profiles_df = data["profiles"]
career_df = data["career"]
skill_df = data["skills"]
signals_df = data["signals"]


print(f"Profiles : {profiles_df.shape}")
print(f"Career   : {career_df.shape}")
print(f"Skills   : {skill_df.shape}")
print(f"Signals  : {signals_df.shape}")

Profiles : (100000, 11)
Career   : (300171, 10)
Skills   : (960302, 5)
Signals  : (100000, 24)

In [4]:
from src.feature_engineering import build_all_features

features = build_all_features(
    profiles_df,
    career_df,
    skill_df,
    signals_df
)

features.head()

,candidate_id,years_of_experience,current_title,total_jobs,unique_companies,avg_job_duration,shortest_job,longest_job,product_company_ratio,service_company_ratio,...,verified_phone,linkedin_connected,expected_salary_min,expected_salary_max,num_skill_assessments,ai_skill_score,production_score,career_quality_score,recruiter_score,trust_score
0,CAND_0000001,6.9,Backend Engineer,2,2,41.000000,27,55,0.0,0.500000,...,1,0,18.7,36.1,4,0.0,20.633333,7.833333,14.182,9.895
1,CAND_0000002,12.5,Operations Manager,4,3,37.250000,14,54,0.0,0.500000,...,0,0,8.8,9.0,0,0.0,51.208333,7.208333,22.844,7.035
2,CAND_0000003,1.1,Customer Support,1,1,13.000000,13,13,0.0,1.000000,...,0,0,11.2,18.1,0,0.0,4.366667,2.666667,3.846,6.895
3,CAND_0000004,3.8,Marketing Manager,3,3,14.666667,10,20,0.0,0.333333,...,1,1,4.6,6.7,0,0.0,22.044444,3.944444,12.599,6.175
4,CAND_0000005,11.0,Accountant,4,4,32.500000,9,52,0.0,0.500000,...,1,1,12.4,19.7,0,0.0,27.416667,7.416667,7.713,9.930

In [5]:
features[
    [
        "retrieval_mentions",
        "ranking_mentions",
        "recommendation_mentions",
        "embeddings_mentions",
        "vector_db_mentions",
        "evaluation_mentions",
        "production_mentions"
    ]
].describe()

,retrieval_mentions,ranking_mentions,recommendation_mentions,embeddings_mentions,vector_db_mentions,evaluation_mentions,production_mentions
count,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000
mean,0.001730,0.010040,0.005210,0.003790,0.001450,0.001270,1.686430
std,0.068169,0.153556,0.092644,0.124883,0.047623,0.063784,1.671667
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000
75%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000
max,5.000000,6.000000,6.000000,9.000000,3.000000,8.000000,12.000000

In [6]:
features = features.fillna(0)

In [7]:
features.head()

,candidate_id,years_of_experience,current_title,total_jobs,unique_companies,avg_job_duration,shortest_job,longest_job,product_company_ratio,service_company_ratio,...,verified_phone,linkedin_connected,expected_salary_min,expected_salary_max,num_skill_assessments,ai_skill_score,production_score,career_quality_score,recruiter_score,trust_score
0,CAND_0000001,6.9,Backend Engineer,2,2,41.000000,27,55,0.0,0.500000,...,1,0,18.7,36.1,4,0.0,20.633333,7.833333,14.182,9.895
1,CAND_0000002,12.5,Operations Manager,4,3,37.250000,14,54,0.0,0.500000,...,0,0,8.8,9.0,0,0.0,51.208333,7.208333,22.844,7.035
2,CAND_0000003,1.1,Customer Support,1,1,13.000000,13,13,0.0,1.000000,...,0,0,11.2,18.1,0,0.0,4.366667,2.666667,3.846,6.895
3,CAND_0000004,3.8,Marketing Manager,3,3,14.666667,10,20,0.0,0.333333,...,1,1,4.6,6.7,0,0.0,22.044444,3.944444,12.599,6.175
4,CAND_0000005,11.0,Accountant,4,4,32.500000,9,52,0.0,0.500000,...,1,1,12.4,19.7,0,0.0,27.416667,7.416667,7.713,9.930

In [8]:
features.describe()

,years_of_experience,total_jobs,unique_companies,avg_job_duration,shortest_job,longest_job,product_company_ratio,service_company_ratio,product_company_count,service_company_count,...,verified_phone,linkedin_connected,expected_salary_min,expected_salary_max,num_skill_assessments,ai_skill_score,production_score,career_quality_score,recruiter_score,trust_score
count,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,...,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000
mean,7.166319,3.001710,2.683100,28.361075,19.188630,38.162800,0.058056,0.310825,0.135550,0.909480,...,0.617890,0.359990,12.172076,19.842671,0.358950,0.041994,26.211854,6.025202,23.834417,7.633368
std,3.824551,1.522442,1.267892,7.819599,9.580271,11.008865,0.181961,0.318863,0.403383,0.910316,...,0.485906,0.479999,5.564816,8.318941,0.772626,1.161883,12.579282,1.465200,15.247883,1.521241
min,1.000000,1.000000,1.000000,8.000000,6.000000,8.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,3.000000,6.000000,0.000000,0.000000,4.000000,1.500000,-6.784000,2.810000
25%,3.900000,2.000000,2.000000,23.250000,13.000000,31.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,7.800000,13.500000,0.000000,0.000000,16.200000,5.083333,13.699750,6.565000
50%,6.800000,3.000000,3.000000,28.000000,16.000000,40.000000,0.000000,0.250000,0.000000,1.000000,...,1.000000,0.000000,11.900000,19.400000,0.000000,0.000000,25.000000,6.111111,21.670000,7.635000
75%,9.900000,4.000000,4.000000,33.000000,24.000000,48.000000,0.000000,0.500000,0.000000,1.000000,...,1.000000,1.000000,15.800000,25.200000,0.000000,0.000000,35.006548,7.000000,30.677250,8.700000
max,16.900000,9.000000,8.000000,98.000000,98.000000,228.000000,1.000000,1.000000,4.000000,7.000000,...,1.000000,1.000000,49.700000,74.500000,5.000000,64.600000,81.550000,16.833333,213.183000,12.725000

In [9]:
signals_df.columns.tolist()

['candidate_id',
 'profile_completeness_score',
 'signup_date',
 'last_active_date',
 'open_to_work_flag',
 'profile_views_received_30d',
 'applications_submitted_30d',
 'recruiter_response_rate',
 'avg_response_time_hours',
 'skill_assessment_scores',
 'connection_count',
 'endorsements_received',
 'notice_period_days',
 'expected_salary_range_inr_lpa',
 'preferred_work_mode',
 'willing_to_relocate',
 'github_activity_score',
 'search_appearance_30d',
 'saved_by_recruiters_30d',
 'interview_completion_rate',
 'offer_acceptance_rate',
 'verified_email',
 'verified_phone',
 'linkedin_connected']

In [10]:
signals_df.head().T

,0,1,2,3,4
candidate_id,CAND_0000001,CAND_0000002,CAND_0000003,CAND_0000004,CAND_0000005
profile_completeness_score,86.9,78.7,31.9,28.5,84.6
signup_date,2025-10-16,2025-07-28,2024-08-02,2025-07-21,2023-10-07
last_active_date,2026-05-20,2025-11-12,2026-03-21,2026-03-25,2025-10-01
open_to_work_flag,True,True,False,False,True
profile_views_received_30d,23,7,1,3,12
applications_submitted_30d,2,1,9,9,2
recruiter_response_rate,0.34,0.29,0.46,0.26,0.37
avg_response_time_hours,177.8,171.6,119.4,104.1,116.7
skill_assessment_scores,"{'NLP': 38.8, 'Image Classification': 64.8, 'F...",{},{},{},{}
connection_count,356,179,19,485,300
endorsements_received,35,3,46,22,14
notice_period_days,60,60,150,120,30
expected_salary_range_inr_lpa,"{'min': 18.7, 'max': 36.1}","{'min': 8.8, 'max': 9.0}","{'min': 11.2, 'max': 18.1}","{'min': 4.6, 'max': 6.7}","{'min': 12.4, 'max': 19.7}"
preferred_work_mode,onsite,flexible,hybrid,onsite,hybrid
willing_to_relocate,False,False,False,True,True
github_activity_score,9.2,-1.0,-1.0,-1.0,-1.0
search_appearance_30d,249,107,28,5,67
saved_by_recruiters_30d,4,10,4,8,1
interview_completion_rate,0.71,0.62,0.86,0.35,0.74
offer_acceptance_rate,0.58,-1.0,-1.0,-1.0,-1.0
verified_email,True,False,True,True,False
verified_phone,True,False,False,True,True
linkedin_connected,False,False,False,True,True

In [11]:
features.shape

(100000, 58)

In [12]:
features.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 58 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   candidate_id                100000 non-null  object
 1   years_of_experience         100000 non-null  float64
 2   current_title               100000 non-null  object
 3   total_jobs                  100000 non-null  int64
 4   unique_companies            100000 non-null  int64
 5   avg_job_duration            100000 non-null  float64
 6   shortest_job                100000 non-null  int64
 7   longest_job                 100000 non-null  int64
 8   product_company_ratio       100000 non-null  float64
 9   service_company_ratio       100000 non-null  float64
 10  product_company_count       100000 non-null  int32
 11  service_company_count       100000 non-null  int32
 12  retrieval_mentions          100000 non-null  int64
 13  ranking_mentions            100000 non-null  int64
 14  recommendation_mentions     100000 non-null  int64
 15  embeddings_mentions         100000 non-null  int64
 16  vector_db_mentions          100000 non-null  int64
 17  evaluation_mentions         100000 non-null  int64
 18  production_mentions         100000 non-null  int64
 19  python_duration             100000 non-null  float64
 20  python_endorsements         100000 non-null  float64
 21  python_proficiency          100000 non-null  float64
 22  embedding_skill_count       100000 non-null  float64
 23  embedding_duration          100000 non-null  float64
 24  embedding_endorsements      100000 non-null  float64
 25  vector_db_skill_count       100000 non-null  float64
 26  vector_db_duration          100000 non-null  float64
 27  vector_db_endorsements      100000 non-null  float64
 28  total_skills                100000 non-null  int64
 29  avg_skill_duration          100000 non-null  float64
 30  total_endorsements          100000 non-null  int64
 31  profile_completeness_score  100000 non-null  float64
 32  open_to_work_flag           100000 non-null  int32
 33  profile_views_received_30d  100000 non-null  int64
 34  applications_submitted_30d  100000 non-null  int64
 35  recruiter_response_rate     100000 non-null  float64
 36  avg_response_time_hours     100000 non-null  float64
 37  connection_count            100000 non-null  int64
 38  endorsements_received       100000 non-null  int64
 39  notice_period_days          100000 non-null  int64
 40  preferred_work_mode         100000 non-null  int32
 41  willing_to_relocate         100000 non-null  int32
 42  github_activity_score       100000 non-null  float64
 43  search_appearance_30d       100000 non-null  int64
 44  saved_by_recruiters_30d     100000 non-null  int64
 45  interview_completion_rate   100000 non-null  float64
 46  offer_acceptance_rate       100000 non-null  float64
 47  verified_email              100000 non-null  int32
 48  verified_phone              100000 non-null  int32
 49  linkedin_connected          100000 non-null  int32
 50  expected_salary_min         100000 non-null  float64
 51  expected_salary_max         100000 non-null  float64
 52  num_skill_assessments       100000 non-null  int64
 53  ai_skill_score              100000 non-null  float64
 54  production_score            100000 non-null  float64
 55  career_quality_score        100000 non-null  float64
 56  recruiter_score             100000 non-null  float64
 57  trust_score                 100000 non-null  float64
dtypes: float64(27), int32(8), int64(21), object(2)
memory usage: 41.2+ MB

In [13]:
features.head()

,candidate_id,years_of_experience,current_title,total_jobs,unique_companies,avg_job_duration,shortest_job,longest_job,product_company_ratio,service_company_ratio,...,verified_phone,linkedin_connected,expected_salary_min,expected_salary_max,num_skill_assessments,ai_skill_score,production_score,career_quality_score,recruiter_score,trust_score
0,CAND_0000001,6.9,Backend Engineer,2,2,41.000000,27,55,0.0,0.500000,...,1,0,18.7,36.1,4,0.0,20.633333,7.833333,14.182,9.895
1,CAND_0000002,12.5,Operations Manager,4,3,37.250000,14,54,0.0,0.500000,...,0,0,8.8,9.0,0,0.0,51.208333,7.208333,22.844,7.035
2,CAND_0000003,1.1,Customer Support,1,1,13.000000,13,13,0.0,1.000000,...,0,0,11.2,18.1,0,0.0,4.366667,2.666667,3.846,6.895
3,CAND_0000004,3.8,Marketing Manager,3,3,14.666667,10,20,0.0,0.333333,...,1,1,4.6,6.7,0,0.0,22.044444,3.944444,12.599,6.175
4,CAND_0000005,11.0,Accountant,4,4,32.500000,9,52,0.0,0.500000,...,1,1,12.4,19.7,0,0.0,27.416667,7.416667,7.713,9.930

In [14]:
features = build_all_features(
    profiles_df,
    career_df,
    skill_df,
    signals_df
)

features[
    [
        "ai_skill_score",
        "production_score",
        "career_quality_score",
        "recruiter_score",
        "trust_score"
    ]
].describe()

,ai_skill_score,production_score,career_quality_score,recruiter_score,trust_score
count,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000
mean,0.041994,26.211854,6.025202,23.834417,7.633368
std,1.161883,12.579282,1.465200,15.247883,1.521241
min,0.000000,4.000000,1.500000,-6.784000,2.810000
25%,0.000000,16.200000,5.083333,13.699750,6.565000
50%,0.000000,25.000000,6.111111,21.670000,7.635000
75%,0.000000,35.006548,7.000000,30.677250,8.700000
max,64.600000,81.550000,16.833333,213.183000,12.725000

In [15]:
features.to_parquet("../data/features.parquet", index=False)