In [9]:
import os
import sys
import pandas as pd

PROJECT_ROOT = os.path.abspath("..")

if PROJECT_ROOT not in sys.path:
    sys.path.append(PROJECT_ROOT)

In [10]:
from src.loader import load_candidates
from src.preprocessing import prepare_data
from src.behavior_scoring import build_behavior_score

In [11]:
candidates = load_candidates()

data = prepare_data(candidates)

signals_df = data["signals"]

In [12]:
behavior_scores = build_behavior_score(signals_df)

In [13]:
behavior_scores.head()

,candidate_id,availability_score,recruiter_interest_score,trust_score,engagement_score,behavior_score
0,CAND_0000001,0.615552,0.116336,0.7476,0.5609,0.506227
1,CAND_0000002,0.605014,0.062919,0.3148,0.2170,0.333844
2,CAND_0000003,0.253581,0.044594,0.3276,0.3010,0.225622
3,CAND_0000004,0.234592,0.074219,0.7140,0.1225,0.267962
4,CAND_0000005,0.698524,0.053481,0.7384,0.2590,0.457334

In [14]:
behavior_scores.describe()

,availability_score,recruiter_interest_score,trust_score,engagement_score,behavior_score
count,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000
mean,0.423280,0.116250,0.566615,0.305709,0.351675
std,0.194311,0.049602,0.180886,0.116205,0.089257
min,0.018311,0.008624,0.100000,0.105000,0.102411
25%,0.269745,0.084748,0.437600,0.219000,0.285614
50%,0.370708,0.107142,0.565600,0.290600,0.341839
75%,0.601481,0.135624,0.699200,0.379300,0.412823
max,0.950920,0.707412,0.999600,0.896300,0.796296

In [15]:
behavior_scores.to_parquet(
    "../data/behavior_scores.parquet",
    index=False
)