In [1]:
import os
import sys

import numpy as np
import pandas as pd

PROJECT_ROOT = os.path.abspath("..")

if PROJECT_ROOT not in sys.path:
    sys.path.append(PROJECT_ROOT)

In [2]:
from src.loader import load_candidates
from src.preprocessing import prepare_data
from src.feature_engineering import build_all_features

In [3]:
candidates = load_candidates()

data = prepare_data(candidates)

features = build_all_features(
    profiles_df=data["profiles"],
    career_df=data["career"],
    skill_df=data["skills"],
    signals_df=data["signals"]
)

In [4]:
semantic_scores = pd.read_parquet(
    "../data/semantic_scores.parquet"
)

behavior_scores = pd.read_parquet(
    "../data/behavior_scores.parquet"
)

In [5]:
ranking_df = (
    features
    .merge(semantic_scores, on="candidate_id")
    .merge(behavior_scores, on="candidate_id")
)

ranking_df.shape

(100000, 64)

In [6]:
from src.ranking import *

In [7]:
technical = build_technical_score(features)

product = build_product_fit_score(features)

experience = build_experience_fit_score(features)

ranking_df = build_final_score(
    ranking_df,
    technical,
    product,
    experience
)

In [8]:
ranking_df = rank_candidates(

    ranking_df

)

In [9]:
ranking_df.head(20)

,candidate_id,years_of_experience,current_title,total_jobs,unique_companies,avg_job_duration,shortest_job,longest_job,product_company_ratio,service_company_ratio,...,semantic_similarity,availability_score,recruiter_interest_score,trust_score,engagement_score,behavior_score,technical_score,product_fit_score,experience_fit_score,final_score
0,CAND_0077337,7.0,Staff Machine Learning Engineer,4,4,20.750000,6,44,0.500000,0.0,...,0.782215,0.907800,0.292314,0.8584,0.6525,0.851117,0.839801,0.804665,1.000000,0.833849
1,CAND_0046064,8.9,Senior NLP Engineer,3,3,35.333333,34,36,0.000000,0.0,...,0.877985,0.876148,0.640024,0.9012,0.4446,0.912841,0.833262,0.521866,0.857143,0.832100
2,CAND_0081846,6.7,Lead AI Engineer,2,2,39.500000,27,52,1.000000,0.0,...,0.849290,0.861580,0.508979,0.9828,0.4864,0.893847,0.654356,1.000000,1.000000,0.827635
3,CAND_0052682,6.6,NLP Engineer,2,2,39.000000,32,46,0.000000,0.0,...,0.752276,0.910898,0.542406,0.9416,0.7678,1.000000,0.864248,0.451895,1.000000,0.817761
4,CAND_0002025,5.9,Senior AI Engineer,2,2,35.000000,28,42,0.000000,0.0,...,0.949568,0.896470,0.381545,0.9272,0.6153,0.886659,0.706972,0.539359,0.857143,0.817090
5,CAND_0008425,7.8,Senior NLP Engineer,3,3,30.666667,21,46,0.000000,0.0,...,0.805199,0.801739,0.674128,0.8288,0.5291,0.891084,0.783039,0.591837,1.000000,0.809577
6,CAND_0083307,7.8,Search Engineer,4,4,23.000000,7,51,0.250000,0.0,...,0.696485,0.773015,0.295603,0.8120,0.5819,0.750593,0.917850,0.667638,1.000000,0.798478
7,CAND_0088025,8.6,Staff Machine Learning Engineer,3,3,34.000000,13,45,0.000000,0.0,...,0.775883,0.843167,0.554380,0.8412,0.7877,0.946947,0.797946,0.521866,0.857143,0.790886
8,CAND_0007009,7.9,Recommendation Systems Engineer,3,3,31.333333,14,48,0.000000,0.0,...,0.635762,0.827429,0.266034,0.7312,0.6199,0.755049,1.000000,0.521866,1.000000,0.787961
9,CAND_0081686,6.0,Search Engineer,3,3,23.666667,13,30,0.333333,0.0,...,0.758746,0.514925,0.458154,0.8288,0.5138,0.664189,0.825023,0.701652,1.000000,0.782862
10,CAND_0080766,8.8,Staff Machine Learning Engineer,4,4,26.250000,12,43,0.250000,0.0,...,0.779605,0.522235,0.675856,0.9680,0.5928,0.809205,0.790035,0.658892,0.857143,0.782856
11,CAND_0069905,6.6,Applied ML Engineer,3,3,26.000000,13,39,0.333333,0.0,...,0.680483,0.795997,0.371092,0.8544,0.6041,0.808003,0.834589,0.727891,1.000000,0.782535
12,CAND_0011162,5.8,Recommendation Systems Engineer,3,3,22.666667,15,28,0.666667,0.0,...,0.627037,0.803910,0.377106,0.9424,0.4736,0.801911,0.886626,0.855199,0.857143,0.776972
13,CAND_0027691,6.5,NLP Engineer,3,3,25.333333,16,33,0.333333,0.0,...,0.705226,0.879932,0.218811,0.9852,0.6735,0.853179,0.738653,0.657920,1.000000,0.762194
14,CAND_0076163,6.9,NLP Engineer,2,2,41.000000,36,46,0.500000,0.0,...,0.683021,0.852705,0.489024,0.9588,0.7152,0.941211,0.712152,0.655977,1.000000,0.759482
15,CAND_0061175,6.7,AI Research Engineer,3,2,26.666667,24,32,0.000000,0.0,...,0.867087,0.654119,0.376878,0.8164,0.4506,0.683327,0.668063,0.495627,1.000000,0.755961
16,CAND_0071974,7.8,Senior AI Engineer,3,3,30.666667,14,50,0.333333,0.0,...,0.849450,0.857019,0.624591,0.9484,0.5831,0.951157,0.439077,0.710398,1.000000,0.742744
17,CAND_0008295,6.5,AI Research Engineer,2,2,38.500000,27,50,0.500000,0.5,...,0.689024,0.920920,0.195620,0.7480,0.6114,0.779230,0.733856,0.597668,1.000000,0.737966
18,CAND_0018499,7.2,Senior Machine Learning Engineer,3,3,28.666667,18,42,0.666667,0.0,...,0.849479,0.826618,0.569206,0.9920,0.7546,0.977866,0.339386,0.881438,1.000000,0.733957
19,CAND_0017960,7.7,Recommendation Systems Engineer,3,3,30.333333,16,54,0.333333,0.0,...,0.619419,0.832178,0.432620,0.6844,0.6008,0.798470,0.777065,0.587949,1.000000,0.728482

In [10]:
ranking_summary = build_submission_features(ranking_df)

ranking_summary.head(20)

,candidate_id,current_title,years_of_experience,semantic_similarity,technical_score,behavior_score,product_fit_score,experience_fit_score,final_score
0,CAND_0077337,Staff Machine Learning Engineer,7.0,0.782215,0.839801,0.851117,0.804665,1.000000,0.833849
1,CAND_0046064,Senior NLP Engineer,8.9,0.877985,0.833262,0.912841,0.521866,0.857143,0.832100
2,CAND_0081846,Lead AI Engineer,6.7,0.849290,0.654356,0.893847,1.000000,1.000000,0.827635
3,CAND_0052682,NLP Engineer,6.6,0.752276,0.864248,1.000000,0.451895,1.000000,0.817761
4,CAND_0002025,Senior AI Engineer,5.9,0.949568,0.706972,0.886659,0.539359,0.857143,0.817090
5,CAND_0008425,Senior NLP Engineer,7.8,0.805199,0.783039,0.891084,0.591837,1.000000,0.809577
6,CAND_0083307,Search Engineer,7.8,0.696485,0.917850,0.750593,0.667638,1.000000,0.798478
7,CAND_0088025,Staff Machine Learning Engineer,8.6,0.775883,0.797946,0.946947,0.521866,0.857143,0.790886
8,CAND_0007009,Recommendation Systems Engineer,7.9,0.635762,1.000000,0.755049,0.521866,1.000000,0.787961
9,CAND_0081686,Search Engineer,6.0,0.758746,0.825023,0.664189,0.701652,1.000000,0.782862
10,CAND_0080766,Staff Machine Learning Engineer,8.8,0.779605,0.790035,0.809205,0.658892,0.857143,0.782856
11,CAND_0069905,Applied ML Engineer,6.6,0.680483,0.834589,0.808003,0.727891,1.000000,0.782535
12,CAND_0011162,Recommendation Systems Engineer,5.8,0.627037,0.886626,0.801911,0.855199,0.857143,0.776972
13,CAND_0027691,NLP Engineer,6.5,0.705226,0.738653,0.853179,0.657920,1.000000,0.762194
14,CAND_0076163,NLP Engineer,6.9,0.683021,0.712152,0.941211,0.655977,1.000000,0.759482
15,CAND_0061175,AI Research Engineer,6.7,0.867087,0.668063,0.683327,0.495627,1.000000,0.755961
16,CAND_0071974,Senior AI Engineer,7.8,0.849450,0.439077,0.951157,0.710398,1.000000,0.742744
17,CAND_0008295,AI Research Engineer,6.5,0.689024,0.733856,0.779230,0.597668,1.000000,0.737966
18,CAND_0018499,Senior Machine Learning Engineer,7.2,0.849479,0.339386,0.977866,0.881438,1.000000,0.733957
19,CAND_0017960,Recommendation Systems Engineer,7.7,0.619419,0.777065,0.798470,0.587949,1.000000,0.728482